# Skeleton: ANNY
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "ANNY"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "root"
"Spine" = "spine05"
"Spine1/2/etc" = "spine04, spine03"
"Chest" = "spine02"
"Chest1/2/etc" = "spine01"
"Neck" = "neck01, neck02, neck03"
"Head" = "head"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "eye.L"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "eye.R"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "clavicle.L"
"LeftUpperArm" = "upperarm01.L"
"LeftLowerArm" = "lowerarm01.L"
"LeftHand" = "wrist.L"
"LeftThumbMetacarpal" = "finger1-1.L"
"LeftThumbProximal" = "finger1-2.L"
"LeftThumbDistal" = "finger1-3.L"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "metacarpal1.L"
"LeftIndexProximal" = "finger2-1.L"
"LeftIndexIntermediate" = "finger2-2.L"
"LeftIndexDistal" = "finger2-3.L"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "metacarpal2.L"
"LeftMiddleProximal" = "finger3-1.L"
"LeftMiddleIntermediate" = "finger3-2.L"
"LeftMiddleDistal" = "finger3-3.L"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "metacarpal3.L"
"LeftRingProximal" = "finger4-1.L"
"LeftRingIntermediate" = "finger4-2.L"
"LeftRingDistal" = "finger4-3.L"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "metacarpal4.L"
"LeftPinkyProximal" = "finger5-1.L"
"LeftPinkyIntermediate" = "finger5-2.L"
"LeftPinkyDistal" = "finger5-3.L"
"LeftPinkyTip" = "-"
"RightShoulder" = "clavicle.R"
"RightUpperArm" = "upperarm01.R"
"RightLowerArm" = "lowerarm01.R"
"RightHand" = "wrist.R"
"RightThumbMetacarpal" = "finger1-1.R"
"RightThumbProximal" = "finger1-2.R"
"RightThumbDistal" = "finger1-3.R"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "metacarpal1.R"
"RightIndexProximal" = "finger2-1.R"
"RightIndexIntermediate" = "finger2-2.R"
"RightIndexDistal" = "finger2-3.R"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "metacarpal2.R"
"RightMiddleProximal" = "finger3-1.R"
"RightMiddleIntermediate" = "finger3-2.R"
"RightMiddleDistal" = "finger3-3.R"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "metacarpal3.R"
"RightRingProximal" = "finger4-1.R"
"RightRingIntermediate" = "finger4-2.R"
"RightRingDistal" = "finger4-3.R"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "metacarpal4.R"
"RightPinkyProximal" = "finger5-1.R"
"RightPinkyIntermediate" = "finger5-2.R"
"RightPinkyDistal" = "finger5-3.R"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "upperleg01.L"
"LeftLowerLeg" = "lowerleg01.L"
"LeftFoot" = "foot.L"
"LeftFoot1" = "-"
"LeftToes" = "toe1-1.L, toe2-1.L, toe3-1.L, toe4-1.L, toe5-1.L"
"LeftToesTip" = "-"
"RightUpperLeg" = "upperleg01.R"
"RightLowerLeg" = "lowerleg01.R"
"RightFoot" = "foot.R"
"RightFoot1" = "-"
"RightToes" = "toe1-1.R, toe2-1.R, toe3-1.R, toe4-1.R, toe5-1.R"
"RightToesTip" = "-"
