# Skeleton: ASF/AMC
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "ASF/AMC"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "pelvis"
"Spine" = "lowerback"
"Spine1/2/etc" = "-"
"Chest" = "upperback / thorax"
"Chest1/2/etc" = "-"
"Neck" = "lowerneck"
"Head" = "head"
"Head1" = "-"
"Jaw" = "opt"
"LeftEye" = "eye_l"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "eye_r"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "lclavicle"
"LeftUpperArm" = "lhumerus"
"LeftLowerArm" = "lradius"
"LeftHand" = "lwrist"
"LeftThumbMetacarpal" = "lthumb"
"LeftThumbProximal" = "-"
"LeftThumbDistal" = "-"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "lindex"
"LeftIndexIntermediate" = "-"
"LeftIndexDistal" = "-"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "-"
"LeftMiddleIntermediate" = "lmiddle"
"LeftMiddleDistal" = "-"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "lring"
"LeftRingIntermediate" = "-"
"LeftRingDistal" = "-"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "lpinky"
"LeftPinkyIntermediate" = "-"
"LeftPinkyDistal" = "-"
"LeftPinkyTip" = "-"
"RightShoulder" = "rclavicle"
"RightUpperArm" = "rhumerus"
"RightLowerArm" = "rradius"
"RightHand" = "rwrist"
"RightThumbMetacarpal" = "rthumb"
"RightThumbProximal" = "-"
"RightThumbDistal" = "-"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "rindex"
"RightIndexIntermediate" = "-"
"RightIndexDistal" = "-"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "rmiddle"
"RightMiddleIntermediate" = "-"
"RightMiddleDistal" = "-"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "rring"
"RightRingIntermediate" = "-"
"RightRingDistal" = "-"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "rpinky"
"RightPinkyIntermediate" = "-"
"RightPinkyDistal" = "-"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "lfemur"
"LeftLowerLeg" = "ltibia"
"LeftFoot" = "lfoot"
"LeftFoot1" = "-"
"LeftToes" = "ltoes"
"LeftToesTip" = "-"
"RightUpperLeg" = "rfemur"
"RightLowerLeg" = "rtibia"
"RightFoot" = "rfoot"
"RightFoot1" = "-"
"RightToes" = "rtoes"
"RightToesTip" = "-"
