# Skeleton: BVH
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "BVH"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "Hips"
"Spine" = "Spine"
"Spine1/2/etc" = "-"
"Chest" = "Spine1 / Spine2"
"Chest1/2/etc" = "-"
"Neck" = "Neck"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "EndSite"
"LeftEye" = "EndSite"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "EndSite"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "LeftShoulder"
"LeftUpperArm" = "LeftArm"
"LeftLowerArm" = "LeftForeArm"
"LeftHand" = "LeftHand"
"LeftThumbMetacarpal" = "-"
"LeftThumbProximal" = "-"
"LeftThumbDistal" = "-"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "-"
"LeftIndexIntermediate" = "-"
"LeftIndexDistal" = "-"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "-"
"LeftMiddleIntermediate" = "-"
"LeftMiddleDistal" = "-"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "-"
"LeftRingIntermediate" = "-"
"LeftRingDistal" = "-"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "-"
"LeftPinkyIntermediate" = "-"
"LeftPinkyDistal" = "-"
"LeftPinkyTip" = "-"
"RightShoulder" = "RightShoulder"
"RightUpperArm" = "RightArm"
"RightLowerArm" = "RightForeArm"
"RightHand" = "RightHand"
"RightThumbMetacarpal" = "-"
"RightThumbProximal" = "-"
"RightThumbDistal" = "-"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "-"
"RightIndexIntermediate" = "-"
"RightIndexDistal" = "-"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "-"
"RightMiddleIntermediate" = "-"
"RightMiddleDistal" = "-"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "-"
"RightRingIntermediate" = "-"
"RightRingDistal" = "-"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "-"
"RightPinkyIntermediate" = "-"
"RightPinkyDistal" = "-"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "LeftUpLeg"
"LeftLowerLeg" = "LeftLeg"
"LeftFoot" = "LeftFoot"
"LeftFoot1" = "-"
"LeftToes" = "EndSite"
"LeftToesTip" = "-"
"RightUpperLeg" = "RightUpLeg"
"RightLowerLeg" = "RightLeg"
"RightFoot" = "RightFoot"
"RightFoot1" = "-"
"RightToes" = "EndSite"
"RightToesTip" = "-"
