# Skeleton: Godot
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "Godot"

[values]
"Root (Parent of e.g. Hips)" = "Root"
"Hips" = "Hips"
"Spine" = "Spine"
"Spine1/2/etc" = "-"
"Chest" = "Chest"
"Chest1/2/etc" = "UpperChest"
"Neck" = "Neck"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "Jaw"
"LeftEye" = "LeftEye"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "RightEye"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "LeftShoulder"
"LeftUpperArm" = "LeftUpperArm"
"LeftLowerArm" = "LeftLowerArm"
"LeftHand" = "LeftHand"
"LeftThumbMetacarpal" = "LeftThumbMetacarpal"
"LeftThumbProximal" = "LeftThumbProximal"
"LeftThumbDistal" = "LeftThumbDistal"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "LeftIndexProximal"
"LeftIndexIntermediate" = "LeftIndexIntermediate"
"LeftIndexDistal" = "LeftIndexDistal"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "LeftMiddleProximal"
"LeftMiddleIntermediate" = "LeftMiddleIntermediate"
"LeftMiddleDistal" = "LeftMiddleDistal"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "LeftRingProximal"
"LeftRingIntermediate" = "LeftRingIntermediate"
"LeftRingDistal" = "LeftRingDistal"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "LeftLittleProximal"
"LeftPinkyIntermediate" = "LeftLittleIntermediate"
"LeftPinkyDistal" = "LeftLittleDistal"
"LeftPinkyTip" = "-"
"RightShoulder" = "RightShoulder"
"RightUpperArm" = "RightUpperArm"
"RightLowerArm" = "RightLowerArm"
"RightHand" = "RightHand"
"RightThumbMetacarpal" = "RightThumbMetacarpal"
"RightThumbProximal" = "RightThumbProximal"
"RightThumbDistal" = "RightThumbDistal"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "RightIndexProximal"
"RightIndexIntermediate" = "RightIndexIntermediate"
"RightIndexDistal" = "RightIndexDistal"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "RightMiddleProximal"
"RightMiddleIntermediate" = "RightMiddleIntermediate"
"RightMiddleDistal" = "RightMiddleDistal"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "RightRingProximal"
"RightRingIntermediate" = "RightRingIntermediate"
"RightRingDistal" = "RightRingDistal"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "RightLittleProximal"
"RightPinkyIntermediate" = "RightLittleIntermediate"
"RightPinkyDistal" = "RightLittleDistal"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "LeftUpperLeg"
"LeftLowerLeg" = "LeftLowerLeg"
"LeftFoot" = "LeftFoot"
"LeftFoot1" = "-"
"LeftToes" = "LeftToes"
"LeftToesTip" = "-"
"RightUpperLeg" = "RightUpperLeg"
"RightLowerLeg" = "RightLowerLeg"
"RightFoot" = "RightFoot"
"RightFoot1" = "-"
"RightToes" = "RightToes"
"RightToesTip" = "-"
