# Skeleton: Mixamo
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "Mixamo"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "Hips"
"Spine" = "Spine"
"Spine1/2/etc" = "-"
"Chest" = "Spine1 / Spine2"
"Chest1/2/etc" = "-"
"Neck" = "Neck"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "LeftEye (optional)"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "RightEye (optional)"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "LeftShoulder"
"LeftUpperArm" = "LeftArm"
"LeftLowerArm" = "LeftForeArm"
"LeftHand" = "LeftHand"
"LeftThumbMetacarpal" = "LeftHandThumb1"
"LeftThumbProximal" = "LeftHandThumb2"
"LeftThumbDistal" = "LeftHandThumb3"
"LeftThumbTip" = "LeftHandThumb4"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "LeftHandIndex1"
"LeftIndexIntermediate" = "LeftHandIndex2"
"LeftIndexDistal" = "LeftHandIndex3"
"LeftIndexTip" = "LeftHandIndex4"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "LeftHandMiddle1"
"LeftMiddleIntermediate" = "LeftHandMiddle2"
"LeftMiddleDistal" = "LeftHandMiddle3"
"LeftMiddleTip" = "LeftHandMiddle4"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "LeftHandRing1"
"LeftRingIntermediate" = "LeftHandRing2"
"LeftRingDistal" = "LeftHandRing3"
"LeftRingTip" = "LeftHandRing4"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "LeftHandPinky1"
"LeftPinkyIntermediate" = "LeftHandPinky2"
"LeftPinkyDistal" = "LeftHandPinky3"
"LeftPinkyTip" = "LeftHandPinky4"
"RightShoulder" = "RightShoulder"
"RightUpperArm" = "RightArm"
"RightLowerArm" = "RightForeArm"
"RightHand" = "RightHand"
"RightThumbMetacarpal" = "RightHandThumb1"
"RightThumbProximal" = "RightHandThumb2"
"RightThumbDistal" = "RightHandThumb3"
"RightThumbTip" = "RightHandThumb4"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "RightHandIndex1"
"RightIndexIntermediate" = "RightHandIndex2"
"RightIndexDistal" = "RightHandIndex3"
"RightIndexTip" = "RightHandIndex4"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "RightHandMiddle1"
"RightMiddleIntermediate" = "RightHandMiddle2"
"RightMiddleDistal" = "RightHandMiddle3"
"RightMiddleTip" = "RightHandMiddle4"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "RightHandRing1"
"RightRingIntermediate" = "RightHandRing2"
"RightRingDistal" = "RightHandRing3"
"RightRingTip" = "RightHandRing4"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "RightHandPinky1"
"RightPinkyIntermediate" = "RightHandPinky2"
"RightPinkyDistal" = "RightHandPinky3"
"RightPinkyTip" = "RightHandPinky4"
"LeftUpperLeg" = "LeftUpLeg"
"LeftLowerLeg" = "LeftLeg"
"LeftFoot" = "LeftFoot"
"LeftFoot1" = "-"
"LeftToes" = "LeftToeBase"
"LeftToesTip" = "-"
"RightUpperLeg" = "RightUpLeg"
"RightLowerLeg" = "RightLeg"
"RightFoot" = "RightFoot"
"RightFoot1" = "-"
"RightToes" = "RightToeBase"
"RightToesTip" = "-"
