# Skeleton: Momentum
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "Momentum"

[values]
"Root (Parent of e.g. Hips)" = "root"
"Hips" = "c_spine0"
"Spine" = "c_spine1"
"Spine1/2/etc" = "c_spine1/c_spine2"
"Chest" = "c_spine3"
"Chest1/2/etc" = "-"
"Neck" = "c_neck"
"Head" = "c_head"
"Head1" = "-"
"Jaw" = "c_jaw"
"LeftEye" = "l_eye"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "r_eye"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "l_clavicle"
"LeftUpperArm" = "l_uparm"
"LeftLowerArm" = "l_lowarm"
"LeftHand" = "l_wrist"
"LeftThumbMetacarpal" = "l_thumb0"
"LeftThumbProximal" = "l_thumb1"
"LeftThumbDistal" = "l_thumb2"
"LeftThumbTip" = "l_thumb_null"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "l_index1"
"LeftIndexIntermediate" = "l_index2"
"LeftIndexDistal" = "l_index3"
"LeftIndexTip" = "l_index_null"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "l_middle1"
"LeftMiddleIntermediate" = "l_middle2"
"LeftMiddleDistal" = "l_middle3"
"LeftMiddleTip" = "l_middle_null"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "l_ring1"
"LeftRingIntermediate" = "l_ring2"
"LeftRingDistal" = "l_ring3"
"LeftRingTip" = "l_ring_null"
"LeftPinkyMetacarpal" = "l_pinky0"
"LeftPinkyProximal" = "l_pinky1"
"LeftPinkyIntermediate" = "l_pinky2"
"LeftPinkyDistal" = "l_pinky3"
"LeftPinkyTip" = "l_pinky_null"
"RightShoulder" = "r_clavicle"
"RightUpperArm" = "r_uparm"
"RightLowerArm" = "r_lowarm"
"RightHand" = "r_wrist"
"RightThumbMetacarpal" = "r_thumb0"
"RightThumbProximal" = "r_thumb1"
"RightThumbDistal" = "r_thumb2"
"RightThumbTip" = "r_thumb_null"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "r_index1"
"RightIndexIntermediate" = "r_index2"
"RightIndexDistal" = "r_index3"
"RightIndexTip" = "r_index_null"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "r_middle1"
"RightMiddleIntermediate" = "r_middle2"
"RightMiddleDistal" = "r_middle3"
"RightMiddleTip" = "r_middle_null"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "r_ring1"
"RightRingIntermediate" = "r_ring2"
"RightRingDistal" = "r_ring3"
"RightRingTip" = "r_ring_null"
"RightPinkyMetacarpal" = "r_pinky0"
"RightPinkyProximal" = "r_pinky1"
"RightPinkyIntermediate" = "r_pinky2"
"RightPinkyDistal" = "r_pinky3"
"RightPinkyTip" = "r_pinky_null"
"LeftUpperLeg" = "l_upleg"
"LeftLowerLeg" = "l_lowleg"
"LeftFoot" = "l_foot"
"LeftFoot1" = "l_talocrural"
"LeftToes" = "l_ball"
"LeftToesTip" = "-"
"RightUpperLeg" = "r_upleg"
"RightLowerLeg" = "r_lowleg"
"RightFoot" = "r_foot"
"RightFoot1" = "r_talocrural"
"RightToes" = "r_ball"
"RightToesTip" = "-"
