# Skeleton: OpenUSD
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "OpenUSD"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "Hips"
"Spine" = "Torso"
"Spine1/2/etc" = "-"
"Chest" = "Chest"
"Chest1/2/etc" = "UpChest"
"Neck" = "Neck"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "LEye"
"Left / Right Eyelids" = "L / R controls x 12"
"LeftEyeTwist" = "-"
"RightEye" = "REye"
"RightEyeTwist" = "-"
"Nose" = "Nose"
"Chin" = "Chin / LChin / RChin"
"Left / Right Ear" = "LEar / REar"
"LeftCheek" = "LCheek"
"RightCheek" = "RCheek"
"Mouth" = "Mouth"
"UpperLip" = "UpLip / LUpLip / RUpLip"
"LowerLip" = "LoLip / LLoLip / RLoLip"
"LeftLipCorner" = "LLipCorner"
"RightLipCorner" = "RLipCorner"
"Brow" = "LBrow / Brow"
"LeftShoulder" = "LShldr"
"LeftUpperArm" = "LArm"
"LeftLowerArm" = "LElbow"
"LeftHand" = "LHand"
"LeftThumbMetacarpal" = "LThumb"
"LeftThumbProximal" = "LThumbMid"
"LeftThumbDistal" = "LThumbTip"
"LeftThumbTip" = "LThumbEnd"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "LIndex"
"LeftIndexIntermediate" = "LIndexMid"
"LeftIndexDistal" = "LIndexTip"
"LeftIndexTip" = "LIndexEnd"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "LMiddle"
"LeftMiddleIntermediate" = "LMiddleMid"
"LeftMiddleDistal" = "LMiddleTip"
"LeftMiddleTip" = "LMiddleEnd"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "LRing"
"LeftRingIntermediate" = "LRingMid"
"LeftRingDistal" = "LRingTip"
"LeftRingTip" = "LRingEnd"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "LPinky"
"LeftPinkyIntermediate" = "LPinkyMid"
"LeftPinkyDistal" = "LPinkyTip"
"LeftPinkyTip" = "LPinkyEnd"
"RightShoulder" = "RShldr"
"RightUpperArm" = "RArm"
"RightLowerArm" = "RElbow"
"RightHand" = "RHand"
"RightThumbMetacarpal" = "RThumb"
"RightThumbProximal" = "RThumbMid"
"RightThumbDistal" = "RThumTip"
"RightThumbTip" = "RThumEnd"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "RIndex"
"RightIndexIntermediate" = "RIndexMid"
"RightIndexDistal" = "RIndexTip"
"RightIndexTip" = "RIndexEnd"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "RMiddle"
"RightMiddleIntermediate" = "RMiddleMid"
"RightMiddleDistal" = "RMiddleTip"
"RightMiddleTip" = "RMiddleEnd"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "RRing"
"RightRingIntermediate" = "RRingMid"
"RightRingDistal" = "RRingTip"
"RightRingTip" = "RRingEnd"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "RPinky"
"RightPinkyIntermediate" = "RPinkyMid"
"RightPinkyDistal" = "RPinkyTip"
"RightPinkyTip" = "RPinkyEnd"
"LeftUpperLeg" = "LLeg"
"LeftLowerLeg" = "LKnee"
"LeftFoot" = "LFoot"
"LeftFoot1" = "-"
"LeftToes" = "LToes"
"LeftToesTip" = "LTip"
"RightUpperLeg" = "RLeg"
"RightLowerLeg" = "RKnee"
"RightFoot" = "RFoot"
"RightFoot1" = "-"
"RightToes" = "RToes"
"RightToesTip" = "RTip"
