# Skeleton: Roblox
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "Roblox"

[values]
"Root (Parent of e.g. Hips)" = "Root/HumanoidRootNode"
"Hips" = "LowerTorso"
"Spine" = "-"
"Spine1/2/etc" = "-"
"Chest" = "UpperTorso"
"Chest1/2/etc" = "-"
"Neck" = "-"
"Head" = "Head/DynamicHead (Opt)"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "-"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "-"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "LeftUpperArm"
"LeftUpperArm" = "-"
"LeftLowerArm" = "LeftLowerArm"
"LeftHand" = "LeftHand"
"LeftThumbMetacarpal" = "-"
"LeftThumbProximal" = "-"
"LeftThumbDistal" = "-"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "-"
"LeftIndexIntermediate" = "-"
"LeftIndexDistal" = "-"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "-"
"LeftMiddleIntermediate" = "-"
"LeftMiddleDistal" = "-"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "-"
"LeftRingIntermediate" = "-"
"LeftRingDistal" = "-"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "-"
"LeftPinkyIntermediate" = "-"
"LeftPinkyDistal" = "-"
"LeftPinkyTip" = "-"
"RightShoulder" = "RightUpperArm"
"RightUpperArm" = "-"
"RightLowerArm" = "RightLowerArm"
"RightHand" = "RightHand"
"RightThumbMetacarpal" = "-"
"RightThumbProximal" = "-"
"RightThumbDistal" = "-"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "-"
"RightIndexIntermediate" = "-"
"RightIndexDistal" = "-"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "-"
"RightMiddleIntermediate" = "-"
"RightMiddleDistal" = "-"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "-"
"RightRingIntermediate" = "-"
"RightRingDistal" = "-"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "-"
"RightPinkyIntermediate" = "-"
"RightPinkyDistal" = "-"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "LeftUpperLeg"
"LeftLowerLeg" = "LeftLowerLeg"
"LeftFoot" = "LeftFoot"
"LeftFoot1" = "-"
"LeftToes" = "-"
"LeftToesTip" = "-"
"RightUpperLeg" = "RightUpperLeg"
"RightLowerLeg" = "RightLowerLeg"
"RightFoot" = "RightFoot"
"RightFoot1" = "-"
"RightToes" = "-"
"RightToesTip" = "-"
