# Skeleton: SecondLife
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "SecondLife"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "mPelvis/PELVIS"
"Spine" = "mTorso/BELLY"
"Spine1/2/etc" = "mSpine1/2/3/4"
"Chest" = "mChest/CHEST"
"Chest1/2/etc" = "-"
"Neck" = "mNeck/NECK"
"Head" = "mHead/HEAD"
"Head1" = "mSkull"
"Jaw" = "mFaceJaw"
"LeftEye" = "mEyeLeft"
"Left / Right Eyelids" = "mFaceEyeLid*"
"LeftEyeTwist" = "-"
"RightEye" = "mEyeRight"
"RightEyeTwist" = "-"
"Nose" = "mFaceNose*"
"Chin" = "mFaceChin"
"Left / Right Ear" = "mFaceEar*"
"LeftCheek" = "mFaceCheek(Upper/Lower)Left"
"RightCheek" = "mFaceCheek(Upper/Lower)Right"
"Mouth" = "-"
"UpperLip" = "mFaceLipUpper*"
"LowerLip" = "mFaceLipLower*"
"LeftLipCorner" = "mFaceLipCornerLeft"
"RightLipCorner" = "mFaceLipCornerRight"
"Brow" = "mFaceEyebrow*"
"LeftShoulder" = "mCollarLeft/L_CLAVICLE"
"LeftUpperArm" = "mShoulderLeft/L_UPPER_ARM"
"LeftLowerArm" = "mElbowLeft/L_LOWER_ARM"
"LeftHand" = "mWristLeft/L_HAND"
"LeftThumbMetacarpal" = "mHandThumb1Left"
"LeftThumbProximal" = "mHandThumb2Left"
"LeftThumbDistal" = "mHandThumb3Left"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "mHandIndex1Left"
"LeftIndexIntermediate" = "mHandIndex2Left"
"LeftIndexDistal" = "mHandIndex3Left"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "mHandMiddle1Left"
"LeftMiddleIntermediate" = "mHandMiddle2Left"
"LeftMiddleDistal" = "mHandMiddle3Left"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "mHandRing1Left"
"LeftRingIntermediate" = "mHandRing2Left"
"LeftRingDistal" = "mHandRing3Left"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "mHandPinky1Left"
"LeftPinkyIntermediate" = "mHandPinky2Left"
"LeftPinkyDistal" = "mHandPinky3Left"
"LeftPinkyTip" = "-"
"RightShoulder" = "mCollarRight/R_CLAVICLE"
"RightUpperArm" = "mShoulderRight/R_UPPER_ARM"
"RightLowerArm" = "mElbowRight/R_LOWER_ARM"
"RightHand" = "mWristRight/R_HAND"
"RightThumbMetacarpal" = "mHandThumb1Right"
"RightThumbProximal" = "mHandThumb2Right"
"RightThumbDistal" = "mHandThumb3Right"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "mHandIndex1Right"
"RightIndexIntermediate" = "mHandIndex2Right"
"RightIndexDistal" = "mHandIndex3Right"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "mHandMiddle1Right"
"RightMiddleIntermediate" = "mHandMiddle2Right"
"RightMiddleDistal" = "mHandMiddle3Right"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "mHandRing1Right"
"RightRingIntermediate" = "mHandRing2Right"
"RightRingDistal" = "mHandRing3Right"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "mHandPinky1Right"
"RightPinkyIntermediate" = "mHandPinky2Right"
"RightPinkyDistal" = "mHandPinky3Right"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "mHipLeft/L_UPPER_LEG"
"LeftLowerLeg" = "mKneeLeft/L_LOWER_LEG"
"LeftFoot" = "mAnkleLeft/L_FOOT"
"LeftFoot1" = "mFootLeft"
"LeftToes" = "mToeLeft"
"LeftToesTip" = "-"
"RightUpperLeg" = "mHipRight/R_UPPER_LEG"
"RightLowerLeg" = "mKneeRight/R_LOWER_LEG"
"RightFoot" = "mAnkleRight/R_FOOT"
"RightFoot1" = "mFootRight"
"RightToes" = "mToeRight"
"RightToesTip" = "-"
