# Skeleton: SMPL
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "SMPL"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "pelvis"
"Spine" = "spine1"
"Spine1/2/etc" = "-"
"Chest" = "spine2"
"Chest1/2/etc" = "-"
"Neck" = "neck"
"Head" = "head"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "-"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "-"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "LShldr"
"LeftUpperArm" = "LArm"
"LeftLowerArm" = "LForeArm"
"LeftHand" = "LHand"
"LeftThumbMetacarpal" = "-"
"LeftThumbProximal" = "-"
"LeftThumbDistal" = "-"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "-"
"LeftIndexIntermediate" = "-"
"LeftIndexDistal" = "-"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "-"
"LeftMiddleIntermediate" = "-"
"LeftMiddleDistal" = "-"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "-"
"LeftRingIntermediate" = "-"
"LeftRingDistal" = "-"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "-"
"LeftPinkyIntermediate" = "-"
"LeftPinkyDistal" = "-"
"LeftPinkyTip" = "-"
"RightShoulder" = "RShldr"
"RightUpperArm" = "RArm"
"RightLowerArm" = "RForeArm"
"RightHand" = "RHand"
"RightThumbMetacarpal" = "-"
"RightThumbProximal" = "-"
"RightThumbDistal" = "-"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "-"
"RightIndexIntermediate" = "-"
"RightIndexDistal" = "-"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "-"
"RightMiddleIntermediate" = "-"
"RightMiddleDistal" = "-"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "-"
"RightRingIntermediate" = "-"
"RightRingDistal" = "-"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "-"
"RightPinkyIntermediate" = "-"
"RightPinkyDistal" = "-"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "LThigh"
"LeftLowerLeg" = "LLeg"
"LeftFoot" = "LFoot"
"LeftFoot1" = "-"
"LeftToes" = "-"
"LeftToesTip" = "-"
"RightUpperLeg" = "RThigh"
"RightLowerLeg" = "RLeg"
"RightFoot" = "RFoot"
"RightFoot1" = "-"
"RightToes" = "-"
"RightToesTip" = "-"
