# Skeleton: UEMannequin
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "UEMannequin"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "Root (Pelvis)"
"Spine" = "Spine_01"
"Spine1/2/etc" = "-"
"Chest" = "Spine_02 / Spine_03"
"Chest1/2/etc" = "-"
"Neck" = "Neck_01"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "opt"
"LeftEye" = "Eye_L"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "Eye_L_Twist"
"RightEye" = "Eye_R"
"RightEyeTwist" = "Eye_R_Twist"
"Nose" = "opt"
"Chin" = "opt"
"Left / Right Ear" = "-"
"LeftCheek" = "opt"
"RightCheek" = "opt"
"Mouth" = "opt"
"UpperLip" = "opt"
"LowerLip" = "opt"
"LeftLipCorner" = "opt"
"RightLipCorner" = "opt"
"Brow" = "opt"
"LeftShoulder" = "Clavicle_L"
"LeftUpperArm" = "UpperArm_L"
"LeftLowerArm" = "LowerArm_L"
"LeftHand" = "Hand_L"
"LeftThumbMetacarpal" = "opt"
"LeftThumbProximal" = "opt"
"LeftThumbDistal" = "opt"
"LeftThumbTip" = "opt"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "opt"
"LeftIndexIntermediate" = "opt"
"LeftIndexDistal" = "opt"
"LeftIndexTip" = "opt"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "opt"
"LeftMiddleIntermediate" = "opt"
"LeftMiddleDistal" = "opt"
"LeftMiddleTip" = "opt"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "opt"
"LeftRingIntermediate" = "opt"
"LeftRingDistal" = "opt"
"LeftRingTip" = "opt"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "opt"
"LeftPinkyIntermediate" = "opt"
"LeftPinkyDistal" = "opt"
"LeftPinkyTip" = "opt"
"RightShoulder" = "Clavicle_R"
"RightUpperArm" = "UpperArm_R"
"RightLowerArm" = "LowerArm_R"
"RightHand" = "Hand_R"
"RightThumbMetacarpal" = "opt"
"RightThumbProximal" = "opt"
"RightThumbDistal" = "opt"
"RightThumbTip" = "opt"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "opt"
"RightIndexIntermediate" = "opt"
"RightIndexDistal" = "opt"
"RightIndexTip" = "opt"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "opt"
"RightMiddleIntermediate" = "opt"
"RightMiddleDistal" = "opt"
"RightMiddleTip" = "opt"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "opt"
"RightRingIntermediate" = "opt"
"RightRingDistal" = "opt"
"RightRingTip" = "opt"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "opt"
"RightPinkyIntermediate" = "opt"
"RightPinkyDistal" = "opt"
"RightPinkyTip" = "opt"
"LeftUpperLeg" = "Thigh_L"
"LeftLowerLeg" = "Calf_L"
"LeftFoot" = "Foot_L"
"LeftFoot1" = "-"
"LeftToes" = "Toe_L (opt)"
"LeftToesTip" = "LeftTip (opt)"
"RightUpperLeg" = "Thigh_R"
"RightLowerLeg" = "Calf_R"
"RightFoot" = "Foot_R"
"RightFoot1" = "-"
"RightToes" = "Toe_R (opt)"
"RightToesTip" = "RightTip (opt)"
