# Skeleton: UEMannequin
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "UEMannequin"

[values]
"Root (Parent of e.g. Hips)" = "-"
"Hips" = "Root (Pelvis)"
"Spine" = "Spine_01"
"Spine1/2/etc" = "-"
"Chest" = "Spine_02 / Spine_03"
"Chest1/2/etc" = "-"
"Neck" = "Neck_01"
"Head" = "Head"
"Head1" = "-"
"Jaw" = "-"
"LeftEye" = "Eye_L"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "Eye_L_Twist"
"RightEye" = "Eye_R"
"RightEyeTwist" = "Eye_R_Twist"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "Clavicle_L"
"LeftUpperArm" = "UpperArm_L"
"LeftLowerArm" = "LowerArm_L"
"LeftHand" = "Hand_L"
"LeftThumbMetacarpal" = "thumb_01_l"
"LeftThumbProximal" = "thumb_02_l"
"LeftThumbDistal" = "thumb_03_l"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "index_metacarpal_l"
"LeftIndexProximal" = "index_01_l"
"LeftIndexIntermediate" = "index_02_l"
"LeftIndexDistal" = "index_03_l"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "middle_metacarpal_l"
"LeftMiddleProximal" = "middle_01_l"
"LeftMiddleIntermediate" = "middle_02_l"
"LeftMiddleDistal" = "middle_03_l"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "ring_metacarpal_l"
"LeftRingProximal" = "ring_01_l"
"LeftRingIntermediate" = "ring_02_l"
"LeftRingDistal" = "ring_03_l"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "pinky_metacarpal_l"
"LeftPinkyProximal" = "pinky_01_l"
"LeftPinkyIntermediate" = "pinky_02_l"
"LeftPinkyDistal" = "pinky_03_l"
"LeftPinkyTip" = "-"
"RightShoulder" = "Clavicle_R"
"RightUpperArm" = "UpperArm_R"
"RightLowerArm" = "LowerArm_R"
"RightHand" = "Hand_R"
"RightThumbMetacarpal" = "thumb_01_r"
"RightThumbProximal" = "thumb_02_r"
"RightThumbDistal" = "thumb_03_r"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "index_metacarpal_r"
"RightIndexProximal" = "index_01_r"
"RightIndexIntermediate" = "index_02_r"
"RightIndexDistal" = "index_03_r"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "middle_metacarpal_r"
"RightMiddleProximal" = "middle_01_r"
"RightMiddleIntermediate" = "middle_02_r"
"RightMiddleDistal" = "middle_03_r"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "ring_metacarpal_r"
"RightRingProximal" = "ring_01_r"
"RightRingIntermediate" = "ring_02_r"
"RightRingDistal" = "ring_03_r"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "pinky_metacarpal_r"
"RightPinkyProximal" = "pinky_01_r"
"RightPinkyIntermediate" = "pinky_02_r"
"RightPinkyDistal" = "pinky_03_r"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "Thigh_L"
"LeftLowerLeg" = "Calf_L"
"LeftFoot" = "Foot_L"
"LeftFoot1" = "-"
"LeftToes" = "Toe_L (opt)"
"LeftToesTip" = "LeftTip (opt)"
"RightUpperLeg" = "Thigh_R"
"RightLowerLeg" = "Calf_R"
"RightFoot" = "Foot_R"
"RightFoot1" = "-"
"RightToes" = "Toe_R (opt)"
"RightToesTip" = "RightTip (opt)"
