# Skeleton: VRM
# canonical joint = this skeleton's joint name ('-' = no mapping).

skeleton = "VRM"

[values]
"Root (Parent of e.g. Hips)" = "root"
"Hips" = "hips"
"Spine" = "spine"
"Spine1/2/etc" = "-"
"Chest" = "chest"
"Chest1/2/etc" = "upperChest"
"Neck" = "neck"
"Head" = "head"
"Head1" = "-"
"Jaw" = "jaw"
"LeftEye" = "leftEye"
"Left / Right Eyelids" = "-"
"LeftEyeTwist" = "-"
"RightEye" = "rightEye"
"RightEyeTwist" = "-"
"Nose" = "-"
"Chin" = "-"
"Left / Right Ear" = "-"
"LeftCheek" = "-"
"RightCheek" = "-"
"Mouth" = "-"
"UpperLip" = "-"
"LowerLip" = "-"
"LeftLipCorner" = "-"
"RightLipCorner" = "-"
"Brow" = "-"
"LeftShoulder" = "leftShoulder"
"LeftUpperArm" = "leftUpperArm"
"LeftLowerArm" = "leftLowerArm"
"LeftHand" = "leftHand"
"LeftThumbMetacarpal" = "leftThumbMetacarpal"
"LeftThumbProximal" = "leftThumbProximal"
"LeftThumbDistal" = "leftThumbDistal"
"LeftThumbTip" = "-"
"LeftIndexMetacarpal" = "-"
"LeftIndexProximal" = "leftIndexProximal"
"LeftIndexIntermediate" = "leftIndexIntermediate"
"LeftIndexDistal" = "leftIndexDistal"
"LeftIndexTip" = "-"
"LeftMiddleMetacarpal" = "-"
"LeftMiddleProximal" = "leftMiddleProximal"
"LeftMiddleIntermediate" = "leftMiddleIntermediate"
"LeftMiddleDistal" = "leftMiddleDistal"
"LeftMiddleTip" = "-"
"LeftRingMetacarpal" = "-"
"LeftRingProximal" = "leftRingProximal"
"LeftRingIntermediate" = "leftRingIntermediate"
"LeftRingDistal" = "leftRingDistal"
"LeftRingTip" = "-"
"LeftPinkyMetacarpal" = "-"
"LeftPinkyProximal" = "leftLittleProximal"
"LeftPinkyIntermediate" = "leftLittleIntermediate"
"LeftPinkyDistal" = "leftLittleDistal"
"LeftPinkyTip" = "-"
"RightShoulder" = "rightShoulder"
"RightUpperArm" = "rightUpperArm"
"RightLowerArm" = "rightLowerArm"
"RightHand" = "rightHand"
"RightThumbMetacarpal" = "rightThumbMetacarpal"
"RightThumbProximal" = "rightThumbProximal"
"RightThumbDistal" = "rightThumbDistal"
"RightThumbTip" = "-"
"RightIndexMetacarpal" = "-"
"RightIndexProximal" = "rightIndexProximal"
"RightIndexIntermediate" = "rightIndexIntermediate"
"RightIndexDistal" = "rightIndexDistal"
"RightIndexTip" = "-"
"RightMiddleMetacarpal" = "-"
"RightMiddleProximal" = "rightMiddleProximal"
"RightMiddleIntermediate" = "rightMiddleIntermediate"
"RightMiddleDistal" = "rightMiddleDistal"
"RightMiddleTip" = "-"
"RightRingMetacarpal" = "-"
"RightRingProximal" = "rightRingProximal"
"RightRingIntermediate" = "rightRingIntermediate"
"RightRingDistal" = "rightRingDistal"
"RightRingTip" = "-"
"RightPinkyMetacarpal" = "-"
"RightPinkyProximal" = "rightLittleProximal"
"RightPinkyIntermediate" = "rightLittleIntermediate"
"RightPinkyDistal" = "rightLittleDistal"
"RightPinkyTip" = "-"
"LeftUpperLeg" = "leftUpperLeg"
"LeftLowerLeg" = "leftLowerLeg"
"LeftFoot" = "leftFoot"
"LeftFoot1" = "-"
"LeftToes" = "leftToes"
"LeftToesTip" = "-"
"RightUpperLeg" = "rightUpperLeg"
"RightLowerLeg" = "rightLowerLeg"
"RightFoot" = "rightFoot"
"RightFoot1" = "-"
"RightToes" = "rightToes"
"RightToesTip" = "-"
